pipeline {
agent any

stages {

    stage('Clone Repository') {
        steps {
            git branch: 'main',
                url: 'https://github.com/jha-aditya67/FLASK-EXPRESS-DOCKER-PROJECT.git'
        }
    }

    stage('Install Dependencies') {
        steps {
            dir('backend') {
                sh '''
                python3 -m venv venv || true
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }
    }

stage('Deploy') {
    steps {
        sh '''
        sudo -u ubuntu bash <<EOF

        cd /home/ubuntu/FLASK-EXPRESS-DOCKER-PROJECT/backend

        python3 -m venv venv || true
        source venv/bin/activate

        pip install -r requirements.txt

        pm2 delete flask-backend || true

        pm2 start app.py \
          --name flask-backend \
          --interpreter /home/ubuntu/FLASK-EXPRESS-DOCKER-PROJECT/backend/venv/bin/python

        pm2 save

        '''
    }
}
}
}


